AWSTemplateFormatVersion: '2010-09-09'
Description: Create a subdomain of poleselli.com with S3, CloudFront, and Route53

Parameters:
  SubDomainName:
    Description: Sub-domain name for poleselli.com
    Type: String
  AcmCertificateArn:
    Description: Arn of the SSL certificate
    Type: String

Resources:
  SubDomainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SubDomainName}.poleselli.com'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
          - Key: project
            Value: poleselli-site

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'SubDomainBucket'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub
              - ${S3Arn}/*
              - S3Arn: !GetAtt  SubDomainBucket.Arn
            Principal:
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${SubDomainName}.poleselli.com'
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 86400
          ForwardedValues:
            QueryString: true
          MaxTTL: 31536000
          TargetOriginId: !Sub 'S3-${SubDomainName}.poleselli.com'
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        IPV6Enabled: true
        Origins:
          - DomainName: !GetAtt SubDomainBucket.DomainName
            Id: !Sub 'S3-${SubDomainName}.poleselli.com'
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudFrontOriginAccessIdentity]]
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: 'TLSv1.1_2016'
          SslSupportMethod: 'sni-only'
      Tags:
        - Key: project
          Value: poleselli-site

  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'CloudFront OAI for ${SubDomainName}.poleselli.com'

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: 'poleselli.com.'
      RecordSets:
      - Name: !Sub '${SubDomainName}.poleselli.com'
        Type: 'A'
        AliasTarget:
          DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
          EvaluateTargetHealth: false
          # The  following HostedZoneId is always used for alias records pointing to CF.
          HostedZoneId: 'Z2FDTNDATAQYW2'
